name: build

on:
  push:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Compile
        run: cl /nologo /O2 /std:c++17 /utf-8 /EHsc /W3 /Fe:hdrprism.exe src\main.cpp
      - uses: actions/upload-artifact@v4
        with:
          name: hdrprism
          path: |
            hdrprism.exe
            hdrprism.ini
